[package]
name = "mandelbrot-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mandelbrot-server"
path = "src/main.rs"

[dependencies]
rocket = "0.5.0-rc.2"
